### ISSUE TITLE
Tree 수정

### ISSUE THREAD

**Issue by eunjungleo** [invisibleinseoul/codelion#2]
manage.py 가 최상단에 오도록 수정

**Comment by kjhchs2** [comment]
![image](https://user-images.githubusercontent.com/72333462/132311215-f743ae72-fa22-4948-9246-183ddcb5b3b6.png)
위와 같은 에러로 인해, 어쩔 수 없이 '--force' 명령어를 사용함
> git push --force origin project1

1. 애초에 readme의 tree를 잘 인지하고 시작했다면 이럴 일 없음.
2. '--force' 명령어는 커밋들이 유실되는 현상이 발생하므로, 협업 시에는 절대 사용하면 안됨.
    어쩔 수 없이 사용해야만 한다면, 기존 코드를 clone 후에 사용해야 한다고 함.
