### ISSUE TITLE
커밋 메세지 작성

### ISSUE THREAD

**Issue by eunjungleo** [invisibleinseoul/codelion#3]
커밋 유형 지정

FEAT : 새로운 기능의 추가
FIX: 버그 수정
DOCS: 문서 수정
STYLE: 스타일 관련 기능(코드 포맷팅, 세미콜론 누락, 코드 자체의 변경이 없는 경우)
REFACTOR: 코드 리펙토링
TEST: 테스트 코트, 리펙토링 테스트 코드 추가
CHORE: 빌드 업무 수정, 패키지 매니저 수정(ex .gitignore 수정 같은 경우)

**Comment by kjhchs2** [comment]
ex1) Feat view detail
ex2) Fix media file line 20:22 in views.py
