### ISSUE TITLE
외래키 저장하는 방법 ( error: NOT NULL constraint failed )

### ISSUE THREAD

**Issue by kjhchs2** [invisibleinseoul/codelion#4]
풀어 쓴 velog : [Link ](https://velog.io/@gojaegaebal/Django-error-NOT-NULL-constraint-failed-%EC%B6%94%EA%B0%80-%EC%84%9C%EC%88%A0-%ED%95%84%EC%9A%94)

comment의 외래키인 post를 저장시켜주는 데 있어서, views.py에 아래와 같이 작성하는 것을 생각했으나 제대로 작동하지 않음.

```
def create_comment(request, post_id):
    comment = CommentModelForm(request.POST)
    comment.post = get_object_or_404(Blog, pk=post_id)
    comment.save()
```

반드시 아래처럼 작성해야 하는데, 명확한 이유를 찾지 못했음..
```
def create_comment(request, post_id):
    comment = CommentModelForm(request.POST)
    tmp_comment = comment.save(commit=False)
    tmp_comment.post = get_object_or_404(Blog, pk=post_id)
    tmp_comment.save()
```

**Comment by kjhchs2** [comment]
'comment'의 type을 print해보면 아래와 같고
<class 'blogapp.forms.CommentModelForm'>

'tmp_comment'의 type을 print해보면 아래와 같다..
<class 'blogapp.models.Comment'>

**Comment by eunjungleo** [comment]
'comment'의 type을 print해보면 아래와 같고
<class 'blogapp.forms.CommentModelForm'>

'tmp_comment'의 type을 print해보면 아래와 같다..
<class 'blogapp.models.Comment'>

이 이유가 맞고 save() method는 model object를 저장할 때만 작동함
